# Generated by Django 5.0.4 on 2024-04-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fibonaccitask',
            options={'ordering': ('date_created',)},
        ),
    ]
